data_dir: "./dataset"
window_size: 60
predict_size: 10
epochs: 60  #60
batch_size: 20      #20
model_type: "rnn"         # Options: "cnn", "transfer"
num_layers: 3
criterion: "mse"
pretrained_weights: null  # Provide path if using transfer model
learning_rate: 0.001
early_stopping_patience: 10
model_save_path: "output_model/rnn_l3.pth"
